# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [master] # only push events on source branch trigger deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: master

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: 安装 Hexo
      run: |
        node -v
        npm install hexo-cli -g
        npm i
        hexo clean
        hexo g

    - name: 缓存 Hexo
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-



    - name: 生成静态文件
      run: |
        hexo clean
        hexo generate

    - name: 部署到Github
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: ggg-hhh/blog
        branch: hexo
        folder: public
        commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"hub.event.head_commit.message }} Updated By Github Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}